development:
  adapter:  postgresql
  host:     <%= ENV['COSTA_DATABASE_HOST'] %>
  encoding: unicode
  database: <%= ENV['COSTA_DATABASE'] %>
  pool:     5
  username: <%= ENV['COSTA_DATABASE_USER'] %>
  password: <%= ENV['COSTA_DATABASE_PASSWORD'] %>
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: costa_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: costa_production
  pool:     5
  template: template0  
  username: costa
  # password: <%= ENV['COSTA_DATABASE_PASSWORD'] %>
  password: postgres
