class FillProvinciaCantonAndDistritoTables < ActiveRecord::Migration
  def up
    execute <<-EOQ
insert into provincias(id,nombre, created_at, updated_at) values(1,'San Jose', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(2,'Alajuela', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(3,'Cartago', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(4,'Heredia', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(5,'Guanacaste', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(6,'Puntarenas', '#{Time.now}', '#{Time.now}');
insert into provincias(id,nombre, created_at, updated_at) values(7,'Limon', '#{Time.now}', '#{Time.now}');


insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,'San Jose', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,'Escazu', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,'Desamparados', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,'Puriscal', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,'Aserri', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,1,'Mora', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,1,'Goicoechea', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,1,'Santa Ana', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(9,1,'Alajuelita', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(10,1,'Vasquez de Coronado', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(11,1,'Acosta', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(12,1,'Tibas', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(13,1,'Moravia', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(14,1,'Montes de Oca', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(15,1,'Turrubares', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(16,1,'Dota', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(17,1,'Curridabat', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(18,1,'Perez Zeledon', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(19,1,'Leon Cortez', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,'Alajuela', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,'San Ramon', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,'Grecia', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,'San Mateo', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,'Atenas', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,2,'Naranjo', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,2,'Palmares', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,2,'Poas', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(9,2,'Orotina', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(10,2,'San Carlos', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(11,2,'Alfaro Ruiz', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(12,2,'Valverde Vega', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(13,2,'Upala', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(14,2,'Los Chiles', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(15,2,'Guatuso', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,'Cartago', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,'Paraiso', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,'La Union', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,'Jimenez', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,'Turrialba', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,'Alvarado', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,'Oreamuno', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,'El Guarco', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,'Heredia', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,'Barva', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,'Santo Domingo', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,4,'Santa Barbara', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,4,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,4,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,4,'Belen', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,4,'Flores', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(9,4,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(10,4,'Sarapiqui', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,'Liberia', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,'Nicoya', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,'Santa Cruz', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,'Bagaces', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,'Carrillo', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,5,'Cañas', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,5,'Abangares', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,5,'Tilaran', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(9,5,'Nandayure', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(10,5,'La Cruz', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(11,5,'Hojancha', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,'Puntarenas', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,'Esparza', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,'Buenos Aires', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,'Montes de Oro', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,6,'Osa', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,6,'Aguirre', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(7,6,'Golfito', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(8,6,'Coto Brus', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(9,6,'Parrita', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(10,6,'Corredores', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(11,6,'Garabito', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,'Limon', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,'Pococi', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,'Siquirres', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,'Talamanca', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(5,7,'Matina', '#{Time.now}', '#{Time.now}');
insert into cantones(canton_id,provincia_id,nombre, created_at, updated_at) values(6,7,'Guacimo', '#{Time.now}', '#{Time.now}');

insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,1,'Carmen', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,1,'Merced', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,1,'Hospital', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,1,'Catedral', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,1,'Zapote', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,1,1,'San Francisco de Dos Rios', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,1,1,'Uruca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,1,1,'Mata Redonda', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,1,1,'Pavas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,1,1,'Hatillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,1,1,'San Sebastian', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,1,'Escazu', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,1,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,1,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,1,'Desamparados', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,1,'San Miguel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,1,'San Juan de Dios', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,1,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,1,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,1,'Frailes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,1,'Patarra', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,1,'San Cristobal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,3,1,'Rosario', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,3,1,'Damas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,3,1,'San Rafael Abajo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,3,1,'Gravillas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,1,'Santiago', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,1,'Mercedes Sur', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,1,'Barbacoas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,4,1,'Grito Alto', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,4,1,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,4,1,'Candelarita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,4,1,'Desamparaditos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,4,1,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,4,1,'Chires', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,4,1,'Tarrazu', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,4,1,'San Marcos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,4,1,'San Lorenzo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(13,4,1,'San Carlos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,1,'Aserri', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,1,'Tarbaca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,1,'Vuelta de Jorco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,1,'San Gabriel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,1,'Legua', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,5,1,'Monterrey', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,5,1,'Salitrillos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,1,'Colon', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,1,'Guayabo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,1,'Tabarcia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,1,'Piedras Negras', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,6,1,'Picagres', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,1,'Guadalupe', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,1,'San Francisco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,1,'Calle Blancos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,1,'Mata de Platano', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,7,1,'Ipis', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,7,1,'Rancho Redondo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,7,1,'Purral', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,1,'Santa Ana', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,1,'Salitral', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,1,'Pozos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,8,1,'Uruca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,8,1,'Piedades', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,8,1,'Brasil', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,9,1,'Alajuelita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,9,1,'San Josecito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,9,1,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,9,1,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,9,1,'San Felipe', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,10,1,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,10,1,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,10,1,'Jesus (Dulce Nombre)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,10,1,'Patalillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,10,1,'Cascajal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,11,1,'San Ignacio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,11,1,'Guaitil', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,11,1,'Palmichal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,11,1,'Cangrejal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,11,1,'Sabanillas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,12,1,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,12,1,'Cinco Esquinas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,12,1,'Anselmo Llorente', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,12,1,'Leon XIII', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,12,1,'Colima', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,13,1,'San Vicente', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,13,1,'San Jeronimo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,13,1,'Trinidad', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,14,1,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,14,1,'Sabanilla', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,14,1,'Mercedes(Betania)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,14,1,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,15,1,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,15,1,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,15,1,'San Juan de Mata', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,15,1,'San Luis', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,16,1,'Santa Maria', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,16,1,'Jardin', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,16,1,'Copey', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,16,1,'Curridabat', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,17,1,'Granadilla', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,17,1,'Sanchez', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,17,1,'Tirrases', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,17,1,'Curridabat', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,18,1,'San Isidro del General', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,18,1,'General', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,18,1,'Daniel Flores', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,18,1,'Rivas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,18,1,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,18,1,'Platanares', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,18,1,'Pejibaye', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,18,1,'Cajon', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,18,1,'Baru', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,18,1,'Rio Nuevo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,18,1,'El Páramo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,19,1,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,19,1,'San Andres', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,19,1,'Llano Bonito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,19,1,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,19,1,'Santa Cruz', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,19,1,'San Antonio', '#{Time.now}', '#{Time.now}');

insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,2,'Alajuela', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,2,'Carrizal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,2,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,2,'Guacima', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,2,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,1,2,'Sabanilla', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,1,2,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,1,2,'Rio Segundo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,1,2,'Desamparados', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,1,2,'Turrucares', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,1,2,'Tambor', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,1,2,'Garita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(13,1,2,'Sarapiqui', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,2,'San Ramon', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,2,'Santiago', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,2,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,2,'Piedades Norte', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,2,'Piedades Sur', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,2,2,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,2,2,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,2,2,'Angeles', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,2,2,'Alfaro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,2,2,'Volio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,2,2,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,2,2,'Zapotal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(13,2,2,'Peñas Blancas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,2,'Grecia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,2,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,2,'San Jose', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,2,'San Roque', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,2,'Tacares', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,2,'Rio Cuarto', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,2,'Puente de Piedra', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,2,'Bolivar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,2,'San Mateo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,2,'Desmonte', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,2,'Jesus Maria', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,2,'Atenas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,2,'Jesus', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,2,'Mercedes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,2,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,2,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,5,2,'San Jose', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,5,2,'Santa Eulalia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,2,'Naranjo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,2,'San Miguel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,2,'San Jose', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,2,'Cirri Sur', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,6,2,'San Jeronimo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,6,2,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,6,2,'Rosario', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,2,'Palmares', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,2,'Zaragoza', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,2,'Buenos Aires', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,2,'Santiago', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,7,2,'Candelaria', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,7,2,'Esquipulas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,7,2,'Granja', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,2,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,2,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,2,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,8,2,'Carrillos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,8,2,'Sabana Redonda', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,9,2,'Orotina', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,9,2,'Mastate', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,9,2,'Hacienda Vieja', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,9,2,'Coyolar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,9,2,'Ceiba', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,10,2,'Quesada', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,10,2,'Florencia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,10,2,'Buenavista', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,10,2,'Aguas Zarcas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,10,2,'Venecia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,10,2,'Pital', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,10,2,'Fortuna', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,10,2,'Tigra', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,10,2,'Palmera', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,10,2,'Venado', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,10,2,'Cutris', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,10,2,'Monterrey', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(13,10,2,'Pocosol', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,11,2,'Zarcero', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,11,2,'Laguna', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,11,2,'Tapezco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,11,2,'Guadalupe', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,11,2,'Palmira', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,11,2,'Zapote', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,11,2,'Brisas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,12,2,'Sarchi Norte', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,12,2,'Sarchi Sur', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,12,2,'Toro Amarillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,12,2,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,12,2,'Rodriguez', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,13,2,'Upala', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,13,2,'Aguas Claras', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,13,2,'San Jose (Pizote)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,13,2,'Bijagua', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,13,2,'Delicias', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,13,2,'Dos Rios (Colonia Mayorga)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,13,2,'Yolillal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,14,2,'Los Chiles', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,14,2,'Caño Negro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,14,2,'El Amparo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,14,2,'San Jorge', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,15,2,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,15,2,'Buena Vista', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,15,2,'Cote', '#{Time.now}', '#{Time.now}');


insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,3,'Oriental', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,3,'Occidental', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,3,'Carmen', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,3,'San Nicolas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,3,'Aguacaliente (San Francisco)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,1,3,'Guadalupe (Arenilla)', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,1,3,'Corralillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,1,3,'Tierra Blanca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,1,3,'Dulce Nombre', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,1,3,'Llano Grande', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,1,3,'Quebradilla', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,3,'Paraiso', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,3,'Santiago', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,3,'Orosi', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,3,'Cachi', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,3,'Llanos de Santa Lucia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,3,'Tres Rios', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,3,'San Diego', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,3,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,3,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,3,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,3,'Dulce Nombre', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,3,'San Ramon', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,3,'Rio Azul', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,3,'Juan Viñas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,3,'Tucurrique', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,3,'Pejibaye', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,3,'Turrialba', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,3,'La Suiza', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,3,'Peralta', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,3,'Santa cruz', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,3,'Santa Teresita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,5,3,'Pavones', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,5,3,'Tuis', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,5,3,'Tayutic', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,5,3,'Santa Rosa', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,5,3,'Tres Equis', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,5,3,'La Isabel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,5,3,'Chirripo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,3,'Pacayas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,3,'Cervantes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,3,'Capellades', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,3,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,3,'Cot', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,3,'Potrero Cerrado', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,3,'Cipreses', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,7,3,'Santa Rosa', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,3,'Tejar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,3,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,3,'Tobosi', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,8,3,'Patio de Agua', '#{Time.now}', '#{Time.now}');

insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,4,'Heredia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,4,'Mercedes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,4,'San Francisco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,4,'Ulloa', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,4,'Varablanca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,4,'Barva', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,4,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,4,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,4,'San Roque', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,4,'Santa Lucia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,2,4,'San Jose de la Montaña', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,4,'Santo Domingo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,4,'San Vicente', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,4,'San Miguel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,4,'Paracito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,4,'Santo Tomas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,4,'Santa Rosa', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,4,'Tures', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,4,'Para', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,4,'Santa Barbara', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,4,'San Pedro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,4,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,4,4,'Jesus', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,4,4,'Santo Domingo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,4,4,'Puraba', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,4,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,4,'San Josecito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,4,'Santiago', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,4,'Angeles', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,4,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,4,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,4,'San Jose', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,4,'Concepcion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,4,'San Francisco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,4,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,4,'Ribera', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,4,'Asuncion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,4,'San Joaquin de Flores', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,4,'Barrantes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,4,'Llorente', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,9,4,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,9,4,'Rincon de Sabanilla', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,10,4,'Puerto Viejo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,10,4,'La Virgen', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,10,4,'Horquetas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,10,4,'Llanuras del Gaspar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,10,4,'Cureña', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,5,'Liberia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,5,'Cañas Dulces', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,5,'Mayorga', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,5,'Nacascolo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,5,'Curubande', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,5,'Nicoya', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,5,'Mansion', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,5,'San Antonio', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,5,'Quebrada Honda', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,5,'Samara', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,2,5,'Nosara', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,2,5,'Belen de Nosarita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,5,'Santa Cruz', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,5,'Bolson', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,5,'Veintisiete de Abril', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,5,'Tempate', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,5,'Cartagena', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,5,'Coajiniquil', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,5,'Diria', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,5,'Cabo Velas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,3,5,'Tamarindo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,5,'Bagaces', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,5,'Fortuna', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,5,'Mogote', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,4,5,'Rio Naranjo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,5,'Filadelfia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,5,'Palmira', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,5,'Sardinal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,5,'Belen', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,5,'Cañas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,5,'Palmira', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,5,'San Miguel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,5,'Bebedero', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,6,5,'Porozal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,5,'Juntas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,5,'Sierra', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,5,'San Juan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,5,'Colorado', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,5,'Tilaran', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,5,'Quebrada Grande', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,5,'Tronadora', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,8,5,'Santa Rosa', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,8,5,'Libano', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,8,5,'Tierras Morenas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,8,5,'Arenal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,9,5,'Carmona', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,9,5,'Santa Rita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,9,5,'Zapotal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,9,5,'San Pablo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,9,5,'Porvenir', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,9,5,'Bejuco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,10,5,'La Cruz', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,10,5,'Santa Cecilia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,10,5,'Garita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,10,5,'Santa Elena', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,11,5,'Hojancha', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,11,5,'Monte Romo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,11,5,'Puerto Carrillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,11,5,'Huacas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,6,'Puntarenas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,6,'Pitahaya', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,6,'Chomes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,6,'Lepanto', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,1,6,'Paquera', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,1,6,'Manzanillo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,1,6,'Guacimal', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,1,6,'Barranca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,1,6,'Monte Verde', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(10,1,6,'Isla del Coco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(11,1,6,'Cobano', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(12,1,6,'Chacarita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(13,1,6,'Chira', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(14,1,6,'Acapulco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(15,1,6,'El Roble', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(16,1,6,'Arancibia', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,6,'Espiritu Santo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,6,'San Juan Grande', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,6,'Macacona', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,6,'San Rafael', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,6,'San Jeronimo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,6,'Buenos Aires', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,6,'Volcan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,6,'Potrero Grande', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,6,'Boruca', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,6,'Pilas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,6,'Colinas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,3,6,'Changuenas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,3,6,'Biolley', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,4,6,'Miramar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,4,6,'Union', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,4,6,'San Isidro', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,6,'Cortes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,6,'Palmar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,6,'Sierpe', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,5,6,'Bahia Ballena', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,5,6,'Piedras Blancas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,6,'Quepos', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,6,'Savegre', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,6,'Naranjito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,7,6,'Golfito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,7,6,'Jimenez', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,7,6,'Guaycar', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,7,6,'Corredor', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,8,6,'San Vito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,8,6,'Sabalito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,8,6,'Aguabuena', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,8,6,'Limoncito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,8,6,'Pittier', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,9,6,'Parrita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,10,6,'Corredores', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,10,6,'La Cuesta', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,10,6,'Canoas', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,10,6,'Laurel', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,11,6,'Jaco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,11,6,'Tarcoles', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,1,7,'Limon', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,1,7,'Valle la Estrella', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,1,7,'Rio Blanco', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,1,7,'Matama', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,2,7,'Guapiles', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,2,7,'Jimenez', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,2,7,'Rita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,2,7,'Roxana', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,2,7,'Cariari', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,2,7,'Colorado', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,3,7,'Siquirres', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,3,7,'Pacuarito', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,3,7,'Florida', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,3,7,'Germania', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,3,7,'Cairo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(6,3,7,'Alegria', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(7,4,7,'Bratsi', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(8,4,7,'Sixaola', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(9,4,7,'Cahuita', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,5,7,'Matina', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,5,7,'Batan', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,5,7,'Carrandi', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(1,6,7,'Guacimo', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(2,6,7,'Mercedes', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(3,6,7,'Pocora', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(4,6,7,'Rio Jimenez', '#{Time.now}', '#{Time.now}');
insert into distritos(distrito_id,canton_id,provincia_id,nombre, created_at, updated_at) values(5,6,7,'Duacari', '#{Time.now}', '#{Time.now}');
EOQ
  end

  def down
    execute <<-SQL
DELETE FROM distritos;
DELETE FROM cantones;
DELETE FROM provincias;
    SQL
  end
end
